# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-FTP
version:      0.02
version_from: FTP.pm
installdirs:  site
requires:
    File::Temp:                    0
    Net::FTP:                      0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
